# Generated by Django 5.1.2 on 2024-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sermon_title", models.CharField(max_length=200)),
                ("sermon_bible", models.CharField(max_length=200)),
                ("insermon_bible", models.JSONField()),
                ("title_kr", models.JSONField()),
                ("title_en", models.JSONField()),
                ("lyrics_list", models.JSONField()),
                ("sequence_list", models.JSONField()),
                ("name", models.CharField(max_length=100)),
                ("preacher", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("aftersermon", models.TextField()),
                ("offering", models.CharField(max_length=200)),
            ],
        ),
    ]
