# Generated by Django 5.1.2 on 2024-10-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Snacklabs_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("part", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
