# Generated by Django 5.1.2 on 2024-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Snacklabs_app", "0002_lyrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
