# Generated by Django 5.1.2 on 2024-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Snacklabs_app",
            "0004_rename_content_lyrics_lyrics_text_remove_lyrics_part_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lyrics",
            name="artist_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lyrics",
            name="song_title",
            field=models.CharField(max_length=255),
        ),
    ]
